### ISSUE TITLE
PUT-request args should be in the body

### ISSUE THREAD

**Issue by ruudvdd** [1up-lab/mailchimp-api-v3#3]
Like a POST request, the args of a PUT-request should be part of the body in json-format, and not the query like it is now.

Reproduce:
`$client->put(sprintf('/3.0/lists/%s/members/%s', $listId, $md5), $body);`

-> Response
{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Invalid Resource","status":400,"detail":"The resource submitted could not be validated. For field-specific details, see the 'errors' array.","instance":"","errors":[{"field":"","message":"Schema describes object, NULL found instead"}]}

**Comment by bytehead** [comment]
Can you test `dev-master`?

**Comment by ruudvdd** [comment]
Hi, I found time to test it and it works great.

**Comment by bytehead** [comment]
Thank you! I'll tag a new release it asap.

**Comment by bytehead** [comment]
Fixed in version [`2.1.3`](https://github.com/1up-lab/mailchimp-api-v3/releases/tag/2.1.3).
