### ISSUE TITLE
Notice after creating a client

### ISSUE THREAD

**Issue by hkodavid** [1up-lab/mailchimp-api-v3#7]
Notice: Undefined offset: 1 in .../vendor/oneup/mailchimp-api-v3/src/Client.php on line 24

System:
Linux homestead 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64
PHP 5.6.34-1+ubuntu16.04.1+deb.sury.org+1

**Comment by bytehead** [comment]
Which version?

**Comment by hkodavid** [comment]
Sorry, I forget, v2.3.1. and my apikey format was a random string.

**Comment by bytehead** [comment]
The `apiKey` has to be the correct format, like `5e3967b6c12afd4455e6f8803a16c7a9-us6`.
